In [1]:
!pip install numpy pandas

Requirement already satisfied: numpy in /Users/leonidkononenko/Desktop/untitled folder/.venv/lib/python3.14/site-packages (2.4.2)
Requirement already satisfied: pandas in /Users/leonidkononenko/Desktop/untitled folder/.venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/leonidkononenko/Desktop/untitled folder/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/leonidkononenko/Desktop/untitled folder/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [7]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]

In [6]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5 5 5 5 5 5 5 5 5 5]
 [10 11 12 13 14 15 16 17 18 19]

In [10]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.004631360205602841 0.9923696431984742 0.497673943826863

In [12]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [13]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False

In [14]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]

In [15]:
M = np.arange(64).reshape(8,8) %2
print(M)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]

In [16]:
M = np.arange(25).reshape(5,5) %5
print(M)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

In [17]:
M = np.random.random((3, 3, 3))
print(M)

[[[0.5454505  0.00940398 0.9516559 ]
  [0.45275267 0.54587739 0.19236399]
  [0.10903685 0.15345854 0.77575323]]

 [[0.01879963 0.36814166 0.96014292]
  [0.38322664 0.63782536 0.26330539]
  [0.61849145 0.39302628 0.78747621]]

 [[0.15435072 0.2618294  0.31195881]
  [0.49742518 0.51845615 0.12125814]
  [0.26936423 0.22328188 0.84750686]]]

In [29]:
n = np.random.randint(3,11)
M = np.ones((n, n))
M[1:-1, 1:-1] = 0
print(M)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

In [19]:
M = np.random.random((10))
print("not sorted", M)
print("sorted", np.sort(M)[::-1])

not sorted [0.61224465 0.75525097 0.28555938 0.65556469 0.78528555 0.23975897
 0.31075916 0.34819328 0.85738805 0.4248568 ]
sorted [0.85738805 0.78528555 0.75525097 0.65556469 0.61224465 0.4248568
 0.34819328 0.31075916 0.28555938 0.23975897]

In [42]:
n = np.random.randint(3, 8)
M = np.random.randint(1,20),(n,n)
# forma, razmer, razmernost = M.shape, M.size, M.ndim
# print(M)
# print("forma ", forma)
# print("razmer ", razmer)
# print("razmernost ", razmernost)

In [43]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [44]:
s1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64

In [47]:
dataframe = pd.DataFrame()
dataframe["Имя"] = ["Джеки Дженсон","Стивен Стивенсон"]
dataframe["Возраст"] = [38, 25]
dataframe["Водитель"] = [True, False]
dataframe

                Имя  Возраст  Водитель
0     Джеки Дженсон       38      True
1  Стивен Стивенсон       25     False

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url) #https://github.com/chrisalbon?tab=repositories в репо нет файла
dataframe.head(5)

HTTPError: HTTP Error 404: Not Found

In [49]:
a = pd.Series([12, 2, 4])
b = pd.Series([9,5,1])
dist = np.sqrt(((a-b) * (a-b)).sum())
print(dist)

5.196152422706632

In [50]:
DF = pd.read_csv('birdkeeper_lungcancer.csv')

In [ ]:
DF = pd.read_csv('birdkeeper_lungcancer.csv')

print('2.2.5')
print(DF.head(2))
print(DF.tail(3))
print(DF.shape)
print(DF.describe())

print('----------------------')

print('2.2.6')

print(DF.iloc[3,4])
print(DF.loc[5, 'cd'])
print(DF.iloc[100:103])

print('----------------------')

print('2.2.7')
print(DF[DF['ss'] == 'Low'].head)

2.2.5
                fm\tss\tbk\tag\tyr\tcd\tlc
0  Male\tLow\tBird\t37\t19\t12\tLungCancer
1  Male\tLow\tBird\t41\t22\t15\tLungCancer
                    fm\tss\tbk\tag\tyr\tcd\tlc
144  Female\tLow\tNoBird\t64\t39\t20\tNoCancer
145   Female\tHigh\tNoBird\t64\t0\t0\tNoCancer
146    Female\tLow\tNoBird\t65\t7\t2\tNoCancer
(147, 1)
                     fm\tss\tbk\tag\tyr\tcd\tlc
count                                       147
unique                                      146
top     Male\tLow\tBird\t64\t42\t20\tLungCancer
freq                                          2
----------------------
2.2.6
                   fm\tss\tbk\tag\tyr\tcd\tlc
100       Male\tLow\tBird\t63\t0\t0\tNoCancer
101  Male\tHigh\tNoBird\t63\t41\t20\tNoCancer
102   Male\tLow\tNoBird\t63\t20\t15\tNoCancer
----------------------

In [57]:
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range= (0, 1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [59]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)

print("srednee:", round(standardized.mean()))
print("standart diviation:", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
srednee: 0
standart diviation: 1.0

In [63]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
dfTest = pd.DataFrame({
    'A': [14.00, 90.20, 90.95, 96.27, 91.21],
    'B': [103.02, 107.26, 110.35, 114.23, 114.68],
    'C': ['big', 'small', 'big', 'small', 'small']
})
scaler = MinMaxScaler()
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])

dfTest

          A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [65]:
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
DF = pd.read_csv(url)

scaler1 = preprocessing.MinMaxScaler()
scaler2 = preprocessing.StandardScaler()

DF[['sepal_length_cm']] = scaler1.fit_transform(DF[['sepal_length_cm']])
DF[['sepal_width_cm']] = scaler2.fit_transform(DF[['sepal_width_cm']])

print(DF.head(15))

    sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0          0.222222        1.032057              1.4             0.2  setosa
1          0.166667       -0.124958              1.4             0.2  setosa
2          0.111111        0.337848              1.3             0.2  setosa
3          0.083333        0.106445              1.5             0.2  setosa
4          0.194444        1.263460              1.4             0.2  setosa
5          0.305556        1.957669              1.7             0.4  setosa
6          0.083333        0.800654              1.4             0.3  setosa
7          0.194444        0.800654              1.5             0.2  setosa
8          0.027778       -0.356361              1.4             0.2  setosa
9          0.166667        0.106445              1.5             0.1  setosa
10         0.305556        1.494863              1.5             0.2  setosa
11         0.138889        0.800654              1.6             0.2  setosa
12         0.138889       -0.124958              1.4             0.1  setosa
13         0.000000       -0.124958              1.1             0.1  setosa
14         0.416667        2.189072              1.2             0.2  setosa